package com.dds.model;
import java.time.LocalDate; // added

import org.springframework.format.annotation.DateTimeFormat;

public class Applicant {
    private int id; // autogenerated
    private String name;
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) //added
    private LocalDate birthdate;
    private String birthPlace;      
    private Sex sex;
    private String cardName;
    private String mamaName;
    private EducationalAttainment educationalAttainment;
    private CivilStatus civilStatus;
    private int numberOfDependents;
    private String tinNumber;
    private String SSSorGSISnumber;
    private CarOwnership carOwnership;
    private String citizenship;
    private String mobileNumber;
    private String homeNumber;
    private String homeAddress;
    private int yearsOfResidence;
    private boolean dosFlag;
    private boolean relDosFlag;
    private String email;
    private String cardAddress;

    @Override
    public String toString() {
        return "Applicant {" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", birthdate=" + birthdate +
                ", birthPlace='" + birthPlace + '\'' +
                ", sex=" + sex +
                ", cardName='" + cardName + '\'' +
                ", mamaName='" + mamaName + '\'' +
                ", educationalAttainment=" + educationalAttainment +
                ", civilStatus=" + civilStatus +
                ", numberOfDependents=" + numberOfDependents +
                ", tinNumber='" + tinNumber + '\'' +
                ", SSSorGSISnumber='" + SSSorGSISnumber + '\'' +
                ", carOwnership=" + carOwnership +
                ", citizenship='" + citizenship + '\'' +
                ", mobileNumber='" + mobileNumber + '\'' +
                ", homeNumber='" + homeNumber + '\'' +
                ", homeAddress='" + homeAddress + '\'' +
                ", yearsOfResidence=" + yearsOfResidence +
                ", dosFlag=" + dosFlag +
                ", relDosFlag=" + relDosFlag +
                ", email='" + email + '\'' +
                ", cardAddress='" + cardAddress + '\'' +
                '}';
    }
    
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDate getBirthdate() {
        return birthdate;
    }

    public void setBirthdate(LocalDate birthdate) {
        this.birthdate = birthdate;
    }

    public String getBirthPlace() {
        return birthPlace;
    }

    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }
    public Sex getSex() {
        return sex;
    }
    public void setSex(Sex sex) {
        this.sex = sex;
    }
    public String getCardName() {
        return cardName;
    }
    public void setCardName(String cardName) {
        this.cardName = cardName;
    }
    public String getMamaName() {
        return mamaName;
    }
    public void setMamaName(String mamaName) {
        this.mamaName = mamaName;
    }
    public EducationalAttainment getEducationalAttainment() {
        return educationalAttainment;
    }
    public void setEducationalAttainment(EducationalAttainment educationalAttainment) {
        this.educationalAttainment = educationalAttainment;
    }
    public CivilStatus getCivilStatus() {
        return civilStatus;
    }
    public void setCivilStatus(CivilStatus civilStatus) {
        this.civilStatus = civilStatus;
    }
    public int getNumberOfDependents() {
        return numberOfDependents;
    }
    public void setNumberOfDependents(int numberOfDependents) {
        this.numberOfDependents = numberOfDependents;
    }
    public String getTinNumber() {
        return tinNumber;
    }
    public void setTinNumber(String tinNumber) {
        this.tinNumber = tinNumber;
    }
    public String getSSSorGSISnumber() {
        return SSSorGSISnumber;
    }
    public void setSSSorGSISnumber(String sSSorGSISnumber) {
        SSSorGSISnumber = sSSorGSISnumber;
    }
    public CarOwnership getCarOwnership() {
        return carOwnership;
    }
    public void setCarOwnership(CarOwnership carOwnership) {
        this.carOwnership = carOwnership;
    }
    public String getCitizenship() {
        return citizenship;
    }
    public void setCitizenship(String citizenship) {
        this.citizenship = citizenship;
    }
    public String getMobileNumber() {
        return mobileNumber;
    }
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public String getHomeNumber() {
        return homeNumber;
    }
    public void setHomeNumber(String homeNumber) {
        this.homeNumber = homeNumber;
    }
    public String getHomeAddress() {
        return homeAddress;
    }
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }
    public int getYearsOfResidence() {
        return yearsOfResidence;
    }
    public void setYearsOfResidence(int yearsOfResidence) {
        this.yearsOfResidence = yearsOfResidence;
    }
    public boolean isDosFlag() {
        return dosFlag;
    }
    public void setDosFlag(boolean dosFlag) {
        this.dosFlag = dosFlag;
    }
    public boolean isRelDosFlag() {
        return relDosFlag;
    }
    public void setRelDosFlag(boolean relDosFlag) {
        this.relDosFlag = relDosFlag;
    }

    public String getCardAddress() {
        return cardAddress;
    }

    public void setCardAddress(String cardAddress) {
        this.cardAddress = cardAddress;
    }
}
