package com.dds.model;

public class DOSRelInfo {
    private int id; // foreign key
    private int relID; // pk, autogenerated
    private String name;
    private String company;
    private String relationship;

    @Override
    public String toString() {
        return "DOSRelInfo {" +
                "id=" + id +
                ", relID=" + relID +
                ", name='" + name + '\'' +
                ", company='" + company + '\'' +
                ", relationship='" + relationship + '\'' +
                '}';
    }
    
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getRelID() {
        return relID;
    }

    public void setRelID(int relID) {
        this.relID = relID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getRelationship() {
        return relationship;
    }

    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }
}
