package com.dds.model;

import java.time.LocalDate;

public class SupplementaryCardHolder {
    private int applicantID; // foreign key
    private int id; // autogenerated
    private String name;
    private LocalDate birthdate;
    private String birthplace;
    private Sex sex;
    private CivilStatus civilStatus;
    private String citizenship;
    private String address;
    private String homeNumber;
    private String mobileNumber;
    private String email;
    private String employer;
    private String employerAddress;
    private String sourceOfFunds;
    private String natureOfBusiness;
    private String officeNumber;
    private String relationshipToPrincipal;

    @Override
    public String toString() {
        return "SupplementaryCardHolder {" +
                "applicantID=" + applicantID +
                ", id=" + id +
                ", name='" + name + '\'' +
                ", birthdate=" + birthdate +
                ", birthplace='" + birthplace + '\'' +
                ", sex=" + sex +
                ", civilStatus=" + civilStatus +
                ", citizenship='" + citizenship + '\'' +
                ", address='" + address + '\'' +
                ", homeNumber='" + homeNumber + '\'' +
                ", mobileNumber='" + mobileNumber + '\'' +
                ", email='" + email + '\'' +
                ", employer='" + employer + '\'' +
                ", employerAddress='" + employerAddress + '\'' +
                ", sourceOfFunds='" + sourceOfFunds + '\'' +
                ", natureOfBusiness='" + natureOfBusiness + '\'' +
                ", officeNumber='" + officeNumber + '\'' +
                ", relationshipToPrincipal='" + relationshipToPrincipal + '\'' +
                '}';
    }
    
    public int getApplicantID() {
        return applicantID;
    }

    public void setApplicantID(int applicantID) {
        this.applicantID = applicantID;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDate getBirthdate() {
        return birthdate;
    }

    public void setBirthdate(LocalDate birthdate) {
        this.birthdate = birthdate;
    }

    public String getBirthplace() {
        return birthplace;
    }

    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace;
    }

    public Sex getSex() {
        return sex;
    }

    public void setSex(Sex sex) {
        this.sex = sex;
    }

    public CivilStatus getCivilStatus() {
        return civilStatus;
    }

    public void setCivilStatus(CivilStatus civilStatus) {
        this.civilStatus = civilStatus;
    }

    public String getCitizenship() {
        return citizenship;
    }

    public void setCitizenship(String citizenship) {
        this.citizenship = citizenship;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getHomeNumber() {
        return homeNumber;
    }

    public void setHomeNumber(String homeNumber) {
        this.homeNumber = homeNumber;
    }

    public String getMobileNumber() {
        return mobileNumber;
    }

    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmployer() {
        return employer;
    }

    public void setEmployer(String employer) {
        this.employer = employer;
    }

    public String getEmployerAddress() {
        return employerAddress;
    }

    public void setEmployerAddress(String employerAddress) {
        this.employerAddress = employerAddress;
    }

    public String getSourceOfFunds() {
        return sourceOfFunds;
    }

    public void setSourceOfFunds(String sourceOfFunds) {
        this.sourceOfFunds = sourceOfFunds;
    }

    public String getNatureOfBusiness() {
        return natureOfBusiness;
    }

    public void setNatureOfBusiness(String natureOfBusiness) {
        this.natureOfBusiness = natureOfBusiness;
    }

    public String getOfficeNumber() {
        return officeNumber;
    }

    public void setOfficeNumber(String officeNumber) {
        this.officeNumber = officeNumber;
    }

    public String getRelationshipToPrincipal() {
        return relationshipToPrincipal;
    }

    public void setRelationshipToPrincipal(String relationshipToPrincipal) {
        this.relationshipToPrincipal = relationshipToPrincipal;
    }
}